version: '3.1'

services:     
    
    rabbit:
        image: rabbitmq:3-management
        deploy:
            restart_policy:
                condition: on-failure      
    influx:
        image: influxdb
        environment:
            INFLUXDB_DB: mydb
        volumes:
            - influx:/var/lib/influxdb               
            
    prise:
        image: xinryxx/prise:latest
        environment:
            RABBIT_HOST: "rabbit"
            RABBIT_PORT: "5672"
            RABBIT_USERNAME: "guest"
            RABBIT_PASSWORD: "guest"
            INFLUX_URI: "http://influx:8086"
        ports:
            - "9081:9081"
            
volumes:
  influx:
